### ISSUE TITLE
Review my addon

### ISSUE THREAD

**Issue by plexx-dev** [FoksVHox/Dan-Video-Suggestions#48]
**Suggestion:**
If you could make a video where you go over addons that we submit.

I think you should go over my wip 

code and say how bad it is andhow its squeezing all performance out of the server

**Gamemode:**

DarkRP

**Relevant resources:**
  
[plexx-reichsbank.zip](https://github.com/FoksVHox/Dan-Video-Suggestions/files/4804002/plexx-reichsbank.zip)

**Comment by plexx-0w0** [comment]
ey fox

**Comment by FoksVHox** [comment]
The title should be useful and not something vague as "Pls read"
